[project]
name = "kronos-rocketpy-sim"
version = "0.1.0"
description = "RocketPy simulation code used in Kronos."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "rocketpy>=1.8.0",
]
